package com.anggasaraya.moviecatalogue.helper

import com.anggasaraya.moviecatalogue.data.local.entity.MovieEntity
import com.anggasaraya.moviecatalogue.data.local.entity.TVShowEntity
import com.anggasaraya.moviecatalogue.data.remote.response.*

object DataDummy {
    fun generateDummyMovies(): ArrayList<MovieEntity> {
        val movies = ArrayList<MovieEntity>()
        movies.add(MovieEntity(id="58138",
                dateReleased="2019-12-19",
                title="백두산",
                genre="Aksi, Petualangan, Cerita Seru",
                userScore="6.4",
                description="Bencana mengguncang Korea secara tak terduga. Ketika Baekdu - gunung tertinggi di Korea meletus dan menyemburkan abu ke atmosfer. Petaka besar kini mengancam Seoul (Korea Selatan) maupun Pyongyang (Korea Utara). Untuk menghadapi bencana ini pakar peledak Korea Selatan (Ha Jung Woo) harus bekerja sama dengan pejabat khusus Korea Utara (Lee Byung Hun) serta pakar geologi nomor satu (Ma Dong Seok) untuk menghentikan bencana dahsyat yang dapat menyebabkan Korea menghilang dari peta dunia untuk selamanya. Sebuah film bencana persembahan Dexter Studios yang telah sukses menghadirkan kisah epik Along With The Gods.",
                status="Released",
                language="Korean",
                budget="17700000", income="61321941",
                imagePath="/1n5q3XpEhCe7TnGHzsHs5pwVT8O.jpg"))
        movies.add(MovieEntity(id="384018",
                dateReleased="2019-08-01",
                title="Fast & Furious Presents: Hobbs & Shaw",
                genre="Aksi, Petualangan, Komedi",
                userScore="6.9",
                description="Hobbs & Shaw (2019) cinema film baru barat yang sangat seru Ini bercerita Luke Hobbs (Dwayne Johnson) terpaksa membentuk aliansi yang mustahil dengan Deckard Shaw (Jason Statham). Keduanya terpaksa bersatu membantu Hattie Shaw (Vanessa Kirby) untuk memburu senjata virus berbahaya dan Brixton (Idris Elba). Brixton adalah penjahat jenis baru yang berhasil mengubah dirinya menjadi manusia super. Keberadaanya menjadi ancaman bagi umat manusia.",
                status="Released",
                language="English",
                budget="200000000",
                income="760098996",
                imagePath="/qRyy2UmjC5ur9bDi3kpNNRCc5nc.jpg"))
        movies.add(MovieEntity(id="647302",
                dateReleased="2019-11-21",
                title="Benny Loves You",
                genre="Kengerian, Komedi",
                userScore="6.0",
                description="Tidak ada deskripsi",
                status="Released",
                language="English",
                budget="0",
                income="0",
                imagePath="/mQ8vALvqA0z0qglG3gI6xpVcslo.jpg"))
        movies.add(MovieEntity(id="475557",
                dateReleased="2019-10-02",
                title="Joker",
                genre="Kejahatan, Cerita Seru, Drama",
                userScore="8.2",
                description="Selama 1980-an, seorang pelawak berdiri gagal didorong gila dan beralih ke kehidupan kejahatan dan kekacauan di Kota Gotham sambil menjadi tokoh kejahatan psikopat terkenal.",
                status="Released",
                language="English",
                budget="55000000",
                income="1074251311",
                imagePath="/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg"))
        movies.add(MovieEntity(id="592350",
                dateReleased="2019-12-20",
                title="僕のヒーローアカデミア THE MOVIE ヒーローズ：ライジング",
                genre="Animasi, Aksi, Fantasi, Petualangan",
                userScore="8.5",
                description="Tidak ada deskripsi",
                status="Released",
                language="Japanese",
                budget="0",
                income="29900850",
                imagePath="/y56HkHAbSZQJjQaxlqCaRI3lIHu.jpg"))
        movies.add(MovieEntity(id="299536",
                dateReleased="2018-04-25",
                title="Avengers: Infinity War",
                genre="Petualangan, Aksi, Cerita Fiksi",
                userScore="8.3",
                description="Karena Avengers dan sekutunya terus melindungi dunia dari ancaman yang terlalu besar untuk ditangani oleh seorang pahlawan, bahaya baru telah muncul dari bayangan kosmik: Thanos. Seorang lalim penghujatan intergalaksi, tujuannya adalah untuk mengumpulkan semua enam Batu Infinity, artefak kekuatan yang tak terbayangkan, dan menggunakannya untuk menimbulkan kehendak memutar pada semua realitas. Segala sesuatu yang telah diperjuangkan oleh Avengers telah berkembang hingga saat ini - nasib Bumi dan keberadaannya sendiri tidak pernah lebih pasti.",
                status="Released", language="English", budget="300000000", income="2046239637", imagePath="/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg"))
        movies.add(MovieEntity(id="335983",
                dateReleased="2018-09-28",
                title="Venom",
                genre="Cerita Fiksi, Aksi",
                userScore="6.8",
                description="Seorang jurnalis, Eddie Brock (Tom Hardy) ingin melakukan sebuah investasi kasus terhadap penemuan yang dipimpin oleh Dr. Carlton Drake (Riz Ahmed). Karena investigasinya, Eddie mengunjungi lab milik Dr. Calrlton Drake. Semuanya ditujukan untuk membuktikan bahwa Dr. Carlton Drake sedang sedang melakukan tindakan jahat menggunakan Symbiote.  Namun, sial bagi Eddie, organisme hidup ini masuk ke dalam tubuhnya. Eddie menemukan kekuatan super dalam dirinya yang mampu mengendalikan semua hal yang ia lakukan.",
                status="Released",
                language="Mandarin",
                budget="116000000",
                income="855013954",
                imagePath="/bURIWlkMbzT8RdpemzCmQECo2Uh.jpg"))
        movies.add(MovieEntity(id="512200",
                dateReleased="2019-12-04",
                title="Jumanji: The Next Level",
                genre="Petualangan, Komedi, Fantasi",
                userScore="7.0",
                description="Dalam Jumanji: The Next Level, keempat sahabat kembali lagi, tetapi permainannya telah berubah. Saat memutuskan masuk lagi ke Jumanji untuk menyelamatkan salah satu dari mereka, mereka menemukan segalanya tak seperti yang diduga. Para pemain harus melaju ke wilayah-wilayah tersembunyi dan belum dijamah, dari gurun nan gersang ke pegunungan bersalju, demi meloloskan diri dari permainan paling berbahaya di dunia.",
                status="Released",
                language="English",
                budget="125000000", income="796575993", imagePath="/odlQgKW9QtStchoyBzy5x0EP2Y8.jpg"))
        movies.add(MovieEntity(id="299534",
                dateReleased="2019-04-24",
                title="Avengers: Endgame",
                genre="Petualangan, Cerita Fiksi, Aksi",
                userScore="8.3",
                description="Terdampar di luar angkasa tanpa persediaan makanan dan minuman, Tony Stark berusaha mengirim pesan untuk Pepper Potts dimana persediaan oksigen mulai menipis. Sementara itu para Avengers yang tersisa harus menemukan cara untuk mengembalikan 50% mahluk di seluruh dunia yang telah dilenyapkan oleh Thanos.",
                status="Released",
                language="English",
                budget="356000000",
                income="2797800564",
                imagePath="/b55H5YuXFPyiCmjDIliFf6EhlUl.jpg"))
        movies.add(MovieEntity(id="461130",
                dateReleased="2019-12-06",
                title="Code 8",
                genre="Cerita Fiksi, Aksi, Kejahatan, Cerita Seru, Drama",
                userScore="6.2",
                description="Di Lincoln City, beberapa penduduk memiliki kemampuan luar biasa. Sebagian besar hidup di bawah garis kemiskinan, di bawah pengawasan ketat dari kepolisian yang sangat militeristis. Connor, seorang pekerja bangunan dengan kekuatan, melibatkan geng kriminal untuk membantu ibunya yang sakit. (Berdasarkan film pendek 'Kode 8,' 2016.)",
                status="Released",
                language="English",
                budget="0",
                income="157209",
                imagePath="/izGX7npHEopDQvngYcxMJEfcFbj.jpg"))
        movies.add(MovieEntity(id="347201",
                dateReleased="2015-08-07",
                title="BORUTO -NARUTO THE MOVIE-",
                genre="Aksi, Komedi, Animasi",
                userScore="7.7",
                description="Tidak ada deskripsi",
                status="Released",
                language="Japanese",
                budget="0",
                income="40200000",
                imagePath="/1k6iwC4KaPvTBt1JuaqXy3noZRY.jpg"))
        movies.add(MovieEntity(id="458156",
                dateReleased="2019-05-15",
                title="John Wick: Chapter 3 - Parabellum",
                genre="Aksi, Cerita Seru, Kejahatan", userScore="7.4", description="Super-pembunuh John Wick kembali dengan label harga $ 14 juta di kepalanya dan sepasukan pembunuh pemburu hadiah di jejaknya. Setelah membunuh anggota guild pembunuh bayang-bayang internasional, High Table, John Wick dikucilkan, tetapi pria dan wanita hit paling kejam di dunia menunggu setiap gilirannya.",
                status="Released",
                language="English",
                budget="55000000",
                income="326709727",
                imagePath="/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg"))
        movies.add(MovieEntity(id="607383",
                dateReleased="2019-07-29",
                title="Aquaslash",
                genre="Kengerian, Komedi",
                userScore="4.1",
                description="Tidak ada deskripsi",
                status="Released",
                language="English",
                budget="0",
                income="0",
                imagePath="/wB8qqLIaYDkYEnjbS5hAJiTuYU6.jpg"))
        movies.add(MovieEntity(id="429617",
                dateReleased="2019-06-28",
                title="Spider-Man: Far From Home",
                genre="Aksi, Petualangan, Cerita Fiksi",
                userScore="7.5",
                description="Peter Parker dan teman-temannya melakukan perjalanan musim panas ke Eropa. Namun, mereka hampir tidak dapat beristirahat - Peter harus setuju untuk membantu Nick Fury mengungkap misteri makhluk yang menyebabkan bencana alam dan kehancuran di seluruh benua.",
                status="Released",
                language="Czech",
                budget="160000000",
                income="1131927996",
                imagePath="/2KLkGP0qWZlNGOad2O6P069hlw0.jpg"))
        movies.add(MovieEntity(id="317442",
                dateReleased="2014-12-06",
                title="The Last: Naruto the Movie",
                genre="Aksi, Percintaan, Animasi",
                userScore="7.8",
                description="Tidak ada deskripsi",
                status="Released",
                language="Japanese",
                budget="1000000",
                income="16500000",
                imagePath="/bAQ8O5Uw6FedtlCbJTutenzPVKd.jpg"))
        movies.add(MovieEntity(id="509967",
                dateReleased="2019-12-10",
                title="6 Underground",
                genre="Aksi, Cerita Seru, Komedi",
                userScore="6.3",
                description="Tidak ada deskripsi",
                status="Released",
                language="English",
                budget="150000000",
                income="0",
                imagePath="/lnWkyG3LLgbbrIEeyl5mK5VRFe4.jpg"))
        movies.add(MovieEntity(id="290859",
                dateReleased="2019-10-23",
                title="Terminator: Dark Fate",
                genre="Aksi, Petualangan, Cerita Fiksi",
                userScore="6.5",
                description="Latar waktu Dark Fate diambil 2 dekade setelah Sarah Connor mencegah Judment Day, mengubah masa depan, dan menulis ulang nasib umat manusia. Dani Ramos (Natalia Reyes) menjalani kehidupan sederhana di Meksiko bersama saudara lelakinya (Diego Boneta) dan ayahnya. Hidup Dani berjalan baik hingga datang seorang Terminator seri Rev-9 (Gabriel Luna) yang sangat canggih dan datang dari masa depan untuk membunuhnya. Kelangsungan hidup Dani bergantung pada kekuatannya bersama Grace (Mackenzie Davis), Grace, seorang manusia super yang juga dikirim dari masa depan dan seorang Sarah Connor (Linda Hamilton). Keduanya membantu Dani melawan Terminator itu. Rev 9 dikirim ke masa lalu untuk menghentikan manusia bangkit dan mengambil alih Skynet. Rev 9 tampak seperti kombinasi dari T-800 dan T-1000, seperti yang terlihat dalam The",
                status="Released",
                language="English",
                budget="185000000",
                income="261119292",
                imagePath="/i8QWXu6dGuTKKerJtnd0A4lUpbv.jpg"))
        movies.add(MovieEntity(id="522938",
                dateReleased="2019-09-19",
                title="Rambo: Last Blood",
                genre="Aksi, Cerita Seru, Drama",
                userScore="6.5",
                description="Ketika putri pengurus rumah tangganya diculik, Rambo melintasi perbatasan AS-Meksiko untuk membawanya pulang tetapi mendapati dirinya menghadapi kekuatan penuh salah satu kartel paling kejam di Meksiko.",
                status="Released",
                language="English",
                budget="50000000",
                income="91490353",
                imagePath="/7u1c5rNsiPLL37Vl6AsBC3bs0ZZ.jpg"))
        movies.add(MovieEntity(id="486589",
                dateReleased="2019-07-25",
                title="Red Shoes And The Seven Dwarfs",
                genre="Animasi, Percintaan, Keluarga",
                userScore="7.8",
                description="Tidak ada deskripsi",
                status="Released",
                language="English",
                budget="0",
                income="5362776",
                imagePath="/MBiKqTsouYqAACLYNDadsjhhC0.jpg"))
        movies.add(MovieEntity(id="505262",
                dateReleased="2018-08-03",
                title="僕のヒーローアカデミア THE MOVIE ～2人の英雄～",
                genre="Animasi, Aksi, Petualangan, Fantasi",
                userScore="8.0",
                description="Tidak ada deskripsi",
                status="Released",
                language="Japanese",
                budget="12000000",
                income="31478826",
                imagePath="/rwLuZhDcLbtC8VKW8Z2xnNKTsAJ.jpg"))
        return movies
    }

    fun generateDummyTVShows(): ArrayList<TVShowEntity> {
        val tvShows = ArrayList<TVShowEntity>()
        tvShows.add(TVShowEntity(id="84958",
                dateReleased="2021-06-09",
                title="Loki",
                genre="Drama, Sci-fi & Fantasy",
                userScore="8.1",
                description="Penjahat lincah Loki melanjutkan perannya sebagai Dewa Mischief setelah peristiwa \"Avengers: Endgame\".",
                status="Returning Series",
                language="English",
                imagePath="/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg"))
        tvShows.add(TVShowEntity(id="76669",
                dateReleased="2018-10-05",
                title="Élite",
                genre="Kejahatan, Misteri, Drama",
                userScore="8.2",
                description="Ketika tiga anak kelas pekerja mendaftar di sekolah paling eksklusif di Spanyol, bentrokan antara siswa kaya dan miskin menyebabkan tragedi.",
                status="Returning Series",
                language="Spanish",
                imagePath="/8fcYtdB6HLP7gsj46OKZ24PjC1g.jpg"))
        tvShows.add(TVShowEntity(id="63174",
                dateReleased="2016-01-25",
                title="Lucifer",
                genre="Kejahatan, Sci-fi & Fantasy",
                userScore="8.5",
                description="Bosan dan tidak bahagia sebagai Penguasa Neraka, Lucifer Morningstar meninggalkan tahtanya dan pensiun ke Los Angeles, di mana ia telah bekerja sama dengan detektif LAPD Chloe Decker untuk menjatuhkan penjahat. Tapi semakin lama dia menjauh dari dunia bawah, semakin besar ancaman bahwa yang terburuk dari umat manusia dapat melarikan diri.",
                status="Returning Series",
                language="English",
                imagePath="/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg"))
        tvShows.add(TVShowEntity(id="60735",
                dateReleased="2014-10-07",
                title="The Flash",
                genre="Drama, Sci-fi & Fantasy",
                userScore="7.7",
                description="Setelah akselerator partikel menyebabkan badai aneh, Penyelidik CSI Barry Allen disambar petir dan jatuh koma. Beberapa bulan kemudian dia terbangun dengan kekuatan kecepatan super, memberinya kemampuan untuk bergerak melalui Central City seperti malaikat penjaga yang tak terlihat. Meskipun awalnya senang dengan kekuatan barunya, Barry terkejut menemukan bahwa dia bukan satu-satunya \"manusia meta\" yang diciptakan setelah ledakan akselerator - dan tidak semua orang menggunakan kekuatan baru mereka untuk kebaikan. Barry bermitra dengan S.T.A.R. Lab dan mendedikasikan hidupnya untuk melindungi yang tidak bersalah. Untuk saat ini, hanya beberapa teman dekat dan rekan yang tahu bahwa Barry secara harfiah adalah manusia tercepat, tetapi tidak lama sebelum dunia mengetahui apa yang menjadi Barry Allen ... The Flash.",
                status="Returning Series",
                language="English",
                imagePath="/wHa6KOJAoNTFLFtp7wguUJKSnju.jpg"))
        tvShows.add(TVShowEntity(id="103768",
                dateReleased="2021-06-04",
                title="Sweet Tooth",
                genre="Drama, Sci-fi & Fantasy",
                userScore="8.0",
                description="Tidak ada deskripsi",
                status="Returning Series",
                language="English",
                imagePath="/rgMfhcrVZjuy5b7Pn0KzCRCEnMX.jpg"))
        tvShows.add(TVShowEntity(id="71712",
                dateReleased="2017-09-25",
                title="The Good Doctor",
                genre="Drama",
                userScore="8.6",
                description="Tidak ada deskripsi",
                status="Returning Series",
                language="English",
                imagePath="/z1K4mJwISETia59rrnMdXxzoSrZ.jpg"))
        tvShows.add(TVShowEntity(id="88396", dateReleased="2021-03-19",
                title="The Falcon and the Winter Soldier",
                genre="Sci-fi & Fantasy, Aksi & Petualangan, Drama, Kejahatan dan Politik",
                userScore="7.8",
                description="Tidak ada deskripsi",
                status="Ended",
                language="English",
                imagePath="/6kbAMLteGO8yyewYau6bJ683sw7.jpg"))
        tvShows.add(TVShowEntity(id="126525",
                dateReleased="2021-06-17",
                title="Elite Histórias Breves: Carla Samuel",
                genre="Drama",
                userScore="7.9",
                description="Tidak ada deskripsi",
                status="Ended",
                language="Spanish",
                imagePath="/wf6QgxmD5dJqqByOCPRj201JYBc.jpg"))
        tvShows.add(TVShowEntity(id="91557",
                dateReleased="2020-01-31",
                title="Ragnarok",
                genre="Drama, Sci-fi & Fantasy, Misteri",
                userScore="8.1",
                description="Tidak ada deskripsi",
                status="Returning Series",
                language="Norwegian",
                imagePath="/1LRLLWGvs5sZdTzuMqLEahb88Pc.jpg"))
        tvShows.add(TVShowEntity(id="1416",
                dateReleased="2005-03-27",
                title="Grey's Anatomy",
                genre="Drama",
                userScore="8.2",
                description="Ikuti kehidupan pribadi dan profesional sekelompok dokter di Rumah Sakit Gray Sloan Memorial di Seattle.",
                status="Returning Series",
                language="English",
                imagePath="/clnyhPqj1SNgpAdeSS6a6fwE6Bo.jpg"))
        tvShows.add(TVShowEntity(id="126526",
                dateReleased="2021-06-15",
                title="Elite Histórias Breves: Nadia Guzmán",
                genre="Drama",
                userScore="8.0",
                description="Tidak ada deskripsi",
                status="Ended",
                language="Spanish", imagePath="/cHHM8eAEWzBX3dbcgYxJnzmtvj3.jpg"))
        tvShows.add(TVShowEntity(id="95057",
                dateReleased="2021-02-23",
                title="Superman & Lois",
                genre="Sci-fi & Fantasy, Aksi & Petualangan, Drama",
                userScore="8.3",
                description="Tidak ada deskripsi",
                status="Returning Series",
                language="English",
                imagePath="/vlv1gn98GqMnKHLSh0dNciqGfBl.jpg"))
        tvShows.add(TVShowEntity(id="60625",
                dateReleased="2013-12-02",
                title="Rick and Morty",
                genre="Animasi, Komedi, Sci-fi & Fantasy, Aksi & Petualangan",
                userScore="8.8",
                description="Rick adalah orang tua yang tidak seimbang secara mental tetapi berbakat secara ilmiah yang baru-baru ini terhubung kembali dengan keluarganya. Dia menghabiskan sebagian besar waktunya dengan melibatkan cucunya yang muda, Morty, dalam petualangan berbahaya dan aneh di luar angkasa dan alam semesta alternatif. Ditambah dengan kehidupan keluarga Morty yang sudah tidak stabil, peristiwa-peristiwa ini menyebabkan Morty sangat tertekan di rumah dan sekolah.",
                status="Returning Series",
                language="English",
                imagePath="/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg"))
        tvShows.add(TVShowEntity(id="96677",
                dateReleased="2021-01-08",
                title="Lupin",
                genre="Kejahatan, Drama, Misteri",
                userScore="7.9",
                description="Tidak ada deskripsi",
                status="Returning Series",
                language="French",
                imagePath="/sgxawbFB5Vi5OkPWQLNfl3dvkNJ.jpg"))
        tvShows.add(TVShowEntity(id="69050",
                dateReleased="2017-01-26",
                title="Riverdale",
                genre="Misteri, Drama, Kejahatan",
                userScore="8.6",
                description="Ditetapkan di masa sekarang, seri ini menawarkan pandangan subversif yang berani pada Archie, Betty, Veronica dan teman-teman mereka, menjelajahi surealitas kehidupan kota kecil, kegelapan dan keanehan yang menggelegak di bawah fasad Riverdale yang sehat.",
                status="Returning Series",
                language="English",
                imagePath="/6zBWSuYW3Ps1nTfeMS8siS4KUaA.jpg"))
        tvShows.add(TVShowEntity(id="85271",
                dateReleased="2021-01-15",
                title="WandaVision",
                genre="Sci-fi & Fantasy, Misteri, Drama",
                userScore="8.4",
                description="Wanda Maximoff dan Vision — dua makhluk bertenaga super yang menjalani kehidupan pinggiran kota yang ideal — mulai curiga bahwa semuanya tidak seperti yang terlihat.",
                status="Ended",
                language="English", imagePath="/frobUz2X5Pc8OiVZU8Oo5K3NKMM.jpg"))
        tvShows.add(TVShowEntity(id="95557",
                dateReleased="2021-03-26",
                title="Invincible",
                genre="Sci-fi & Fantasy, Animasi, Aksi & Petualangan, Drama, userScore=8.9",
                description="Mark Grayson adalah remaja normal kecuali fakta bahwa ayahnya adalah pahlawan super paling kuat di planet ini. Tak lama setelah ulang tahunnya yang ketujuh belas, Mark mulai mengembangkan kekuatannya sendiri dan masuk ke dalam pengawasan ayahnya.",
                status="Returning Series",
                language="English",
                imagePath="/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg"))
        tvShows.add(TVShowEntity(id="1399",
                dateReleased="2011-04-17",
                title="Game of Thrones",
                genre="Sci-fi & Fantasy, Drama, Aksi & Petualangan",
                userScore="8.4",
                description="Tujuh keluarga bangsawan berjuang untuk menguasai tanah mitos Westeros. Gesekan antara rumah-rumah mengarah ke perang skala penuh. Semua sementara kejahatan yang sangat kuno terbangun di utara terjauh. Di tengah-tengah perang, perintah militer yang diabaikan, Night's Watch, adalah yang berdiri di antara alam manusia dan kengerian es di luarnya.",
                status="Ended",
                language="English",
                imagePath="/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg"))
        tvShows.add(TVShowEntity(id="79460",
                dateReleased="2018-10-25",
                title="Legacies",
                genre="Sci-fi & Fantasy, Drama",
                userScore="8.6",
                description="Tidak ada deskripsi",
                status="Returning Series",
                language="English",
                imagePath="/qTZIgXrBKURBK1KrsT7fe3qwtl9.jpg"))
        tvShows.add(TVShowEntity(id="80240",
                dateReleased="2018-06-12",
                title="La Reina del Flow",
                genre="Drama",
                userScore="8.0",
                description="Tidak ada deskripsi",
                status="Returning Series",
                language="Spanish",
                imagePath="/fuVuDYrs8sxvEolnYr0wCSvtyTi.jpg"))
        return tvShows
    }

    fun generateDummyMoviesResponse(): ArrayList<ResultsItemMovie>{
        val movies = ArrayList<ResultsItemMovie>()
        movies.add(ResultsItemMovie(
            "Bencana mengguncang Korea secara tak terduga. Ketika Baekdu - gunung tertinggi di Korea meletus dan menyemburkan abu ke atmosfer. Petaka besar kini mengancam Seoul (Korea Selatan) maupun Pyongyang (Korea Utara). Untuk menghadapi bencana ini pakar peledak Korea Selatan (Ha Jung Woo) harus bekerja sama dengan pejabat khusus Korea Utara (Lee Byung Hun) serta pakar geologi nomor satu (Ma Dong Seok) untuk menghentikan bencana dahsyat yang dapat menyebabkan Korea menghilang dari peta dunia untuk selamanya. Sebuah film bencana persembahan Dexter Studios yang telah sukses menghadirkan kisah epik Along With The Gods.",
            "ko",
            "백두산",
            false,
            "Ashfall",
            listOf(28, 12, 53),
            "/arHW8z3uHVknHc24dvc1pQvxjw.jpg",
            "/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg",
            "2019-12-19",
            608.219,
            6.4,
            581387,
            false,
            276))
        movies.add(ResultsItemMovie(
            "Hobbs & Shaw (2019) cinema film baru barat yang sangat seru Ini bercerita Luke Hobbs (Dwayne Johnson) terpaksa membentuk aliansi yang mustahil dengan Deckard Shaw (Jason Statham). Keduanya terpaksa bersatu membantu Hattie Shaw (Vanessa Kirby) untuk memburu senjata virus berbahaya dan Brixton (Idris Elba). Brixton adalah penjahat jenis baru yang berhasil mengubah dirinya menjadi manusia super. Keberadaanya menjadi ancaman bagi umat manusia.",
            "en",
            "Fast & Furious Presents: Hobbs & Shaw",
            false,
            "Fast & Furious Presents: Hobbs & Shaw",
            listOf(28, 12, 35),
            "/qRyy2UmjC5ur9bDi3kpNNRCc5nc.jpg",
            "/qAhedRxRYWZAgZ8O8pHIl6QHdD7.jpg",
            "2019-08-01",
            606.95,
            6.9,
            384018,
            false,
            4984))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/czHYg6LQ5926OL8wj5kC09pNR12.jpg",
            genreIds= listOf(27, 35),
            id= 647302,
            originalLanguage= "en",
            originalTitle= "Benny Loves You",
            overview= "",
            popularity= 384.662,
            posterPath= "/mQ8vALvqA0z0qglG3gI6xpVcslo.jpg",
            releaseDate= "2019-11-21",
            title= "Benny Loves You",
            video= false,
            voteAverage= 6.0,
            voteCount= 40
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
            genreIds= listOf(80, 53, 18),
            id= 475557,
            originalLanguage= "en",
            originalTitle= "Joker",
            overview= "Selama 1980-an, seorang pelawak berdiri gagal didorong gila dan beralih ke kehidupan kejahatan dan kekacauan di Kota Gotham sambil menjadi tokoh kejahatan psikopat terkenal.",
            popularity= 410.731,
            posterPath= "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
            releaseDate= "2019-10-02",
            title= "Joker",
            video= false,
            voteAverage= 8.2,
            voteCount= 17877
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/9guoVF7zayiiUq5ulKQpt375VIy.jpg",
            genreIds= listOf(16, 28, 14, 12),
            id= 592350,
            originalLanguage= "ja",
            originalTitle= "僕のヒーローアカデミア THE MOVIE ヒーローズ：ライジング",
            overview= "",
            popularity= 351.742,
            posterPath= "/y56HkHAbSZQJjQaxlqCaRI3lIHu.jpg",
            releaseDate= "2019-12-20",
            title= "僕のヒーローアカデミア THE MOVIE ヒーローズ：ライジング",
            video= false,
            voteAverage= 8.5,
            voteCount= 735
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
            genreIds= listOf(12, 28, 878),
            id= 299536,
            originalLanguage= "en",
            originalTitle= "Avengers: Infinity War",
            overview= "Karena Avengers dan sekutunya terus melindungi dunia dari ancaman yang terlalu besar untuk ditangani oleh seorang pahlawan, bahaya baru telah muncul dari bayangan kosmik: Thanos. Seorang lalim penghujatan intergalaksi, tujuannya adalah untuk mengumpulkan semua enam Batu Infinity, artefak kekuatan yang tak terbayangkan, dan menggunakannya untuk menimbulkan kehendak memutar pada semua realitas. Segala sesuatu yang telah diperjuangkan oleh Avengers telah berkembang hingga saat ini - nasib Bumi dan keberadaannya sendiri tidak pernah lebih pasti.",
            popularity= 364.82,
            posterPath= "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
            releaseDate= "2018-04-25",
            title= "Avengers: Infinity War",
            video= false,
            voteAverage= 8.3,
            voteCount= 22017
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg",
            genreIds= listOf(878, 28),
            id= 335983,
            originalLanguage= "en",
            originalTitle= "Venom",
            overview= "Seorang jurnalis, Eddie Brock (Tom Hardy) ingin melakukan sebuah investasi kasus terhadap penemuan yang dipimpin oleh Dr. Carlton Drake (Riz Ahmed). Karena investigasinya, Eddie mengunjungi lab milik Dr. Calrlton Drake. Semuanya ditujukan untuk membuktikan bahwa Dr. Carlton Drake sedang sedang melakukan tindakan jahat menggunakan Symbiote.  Namun, sial bagi Eddie, organisme hidup ini masuk ke dalam tubuhnya. Eddie menemukan kekuatan super dalam dirinya yang mampu mengendalikan semua hal yang ia lakukan.",
            popularity= 269.256,
            posterPath= "/bURIWlkMbzT8RdpemzCmQECo2Uh.jpg",
            releaseDate= "2018-09-28",
            title= "Venom",
            video= false,
            voteAverage= 6.8,
            voteCount= 10910
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg",
            genreIds= listOf(12, 35, 14),
            id= 512200,
            originalLanguage= "en",
            originalTitle= "Jumanji: The Next Level",
            overview= "Dalam Jumanji: The Next Level, keempat sahabat kembali lagi, tetapi permainannya telah berubah. Saat memutuskan masuk lagi ke Jumanji untuk menyelamatkan salah satu dari mereka, mereka menemukan segalanya tak seperti yang diduga. Para pemain harus melaju ke wilayah-wilayah tersembunyi dan belum dijamah, dari gurun nan gersang ke pegunungan bersalju, demi meloloskan diri dari permainan paling berbahaya di dunia.",
            popularity= 263.224,
            posterPath= "/odlQgKW9QtStchoyBzy5x0EP2Y8.jpg",
            releaseDate= "2019-12-04",
            title= "Jumanji: The Next Level",
            video= false,
            voteAverage= 7.0,
            voteCount= 5884
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
            genreIds= listOf(12, 878, 28),
            id= 299534,
            originalLanguage= "en",
            originalTitle= "Avengers: Endgame",
            overview= "Terdampar di luar angkasa tanpa persediaan makanan dan minuman, Tony Stark berusaha mengirim pesan untuk Pepper Potts dimana persediaan oksigen mulai menipis. Sementara itu para Avengers yang tersisa harus menemukan cara untuk mengembalikan 50% mahluk di seluruh dunia yang telah dilenyapkan oleh Thanos.",
            popularity= 271.522,
            posterPath= "/b55H5YuXFPyiCmjDIliFf6EhlUl.jpg",
            releaseDate= "2019-04-24",
            title= "Avengers: Endgame",
            video= false,
            voteAverage= 8.3,
            voteCount= 18358
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/wlnDNMQlnwl5ETlVY6n9CEtR5s0.jpg",
            genreIds= listOf(878, 28, 80, 53, 18),
            id= 461130,
            originalLanguage= "en",
            originalTitle= "Code 8",
            overview= "Di Lincoln City, beberapa penduduk memiliki kemampuan luar biasa. Sebagian besar hidup di bawah garis kemiskinan, di bawah pengawasan ketat dari kepolisian yang sangat militeristis. Connor, seorang pekerja bangunan dengan kekuatan, melibatkan geng kriminal untuk membantu ibunya yang sakit. (Berdasarkan film pendek 'Kode 8,' 2016.)",
            popularity= 245.355,
            posterPath= "/izGX7npHEopDQvngYcxMJEfcFbj.jpg",
            releaseDate= "2019-12-06",
            title= "Code 8",
            video= false,
            voteAverage= 6.2,
            voteCount= 1236
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/zLTfRrrVXNW3OWUk6U1eFZhB18m.jpg",
            genreIds= listOf(28, 35, 16),
            id= 347201,
            originalLanguage= "ja",
            originalTitle= "BORUTO -NARUTO THE MOVIE-",
            overview= "",
            popularity= 269.987,
            posterPath= "/1k6iwC4KaPvTBt1JuaqXy3noZRY.jpg",
            releaseDate= "2015-08-07",
            title= "BORUTO -NARUTO THE MOVIE-",
            video= false,
            voteAverage= 7.7,
            voteCount= 791
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/vVpEOvdxVBP2aV166j5Xlvb5Cdc.jpg",
            genreIds= listOf(28, 53, 80),
            id= 458156,
            originalLanguage= "en",
            originalTitle= "John Wick: Chapter 3 - Parabellum",
            overview= "Super-pembunuh John Wick kembali dengan label harga $ 14 juta di kepalanya dan sepasukan pembunuh pemburu hadiah di jejaknya. Setelah membunuh anggota guild pembunuh bayang-bayang internasional, High Table, John Wick dikucilkan, tetapi pria dan wanita hit paling kejam di dunia menunggu setiap gilirannya.",
            popularity= 227.305,
            posterPath= "/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg",
            releaseDate= "2019-05-15",
            title= "John Wick: Chapter 3 - Parabellum",
            video= false,
            voteAverage= 7.4,
            voteCount= 6859
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/eqVgQwv8HfDN2tv4XWhqW5GryV4.jpg",
            genreIds= listOf(27, 35),
            id= 607383,
            originalLanguage= "en",
            originalTitle= "Aquaslash",
            overview= "",
            popularity= 226.123,
            posterPath= "/wB8qqLIaYDkYEnjbS5hAJiTuYU6.jpg",
            releaseDate= "2019-07-29",
            title= "Aquaslash",
            video= false,
            voteAverage= 4.1,
            voteCount= 62
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/8XiTPU1zfy41Xgg96TCHXj4uQJf.jpg",
            genreIds= listOf(28, 12, 878),
            id= 429617,
            originalLanguage= "en",
            originalTitle= "Spider-Man: Far From Home",
            overview= "Peter Parker dan teman-temannya melakukan perjalanan musim panas ke Eropa. Namun, mereka hampir tidak dapat beristirahat - Peter harus setuju untuk membantu Nick Fury mengungkap misteri makhluk yang menyebabkan bencana alam dan kehancuran di seluruh benua.",
            popularity= 222.691,
            posterPath= "/2KLkGP0qWZlNGOad2O6P069hlw0.jpg",
            releaseDate= "2019-06-28",
            title= "Spider-Man: Far From Home",
            video= false,
            voteAverage= 7.5,
            voteCount= 10020
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/kzIiKLccwuzD3qD5OHFyPIkiqEw.jpg",
            genreIds= listOf(28, 10749, 16),
            id= 317442,
            originalLanguage= "ja",
            originalTitle= "The Last: Naruto the Movie",
            overview= "",
            popularity= 229.96,
            posterPath= "/bAQ8O5Uw6FedtlCbJTutenzPVKd.jpg",
            releaseDate= "2014-12-06",
            title= "The Last: Naruto the Movie",
            video= false,
            voteAverage= 7.8,
            voteCount= 939
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/eFw5YSorHidsajLTayo1noueIxI.jpg",
            genreIds= listOf(28, 53, 35),
            id= 509967,
            originalLanguage= "en",
            originalTitle= "6 Underground",
            overview= "",
            popularity= 194.934,
            posterPath= "/lnWkyG3LLgbbrIEeyl5mK5VRFe4.jpg",
            releaseDate= "2019-12-10",
            title= "6 Underground",
            video= false,
            voteAverage= 6.3,
            voteCount= 3164
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/a6cDxdwaQIFjSkXf7uskg78ZyTq.jpg",
            genreIds= listOf(28, 12, 878),
            id= 290859,
            originalLanguage= "en",
            originalTitle= "Terminator: Dark Fate",
            overview= "Latar waktu Dark Fate diambil 2 dekade setelah Sarah Connor mencegah Judment Day, mengubah masa depan, dan menulis ulang nasib umat manusia. Dani Ramos (Natalia Reyes) menjalani kehidupan sederhana di Meksiko bersama saudara lelakinya (Diego Boneta) dan ayahnya. Hidup Dani berjalan baik hingga datang seorang Terminator seri Rev-9 (Gabriel Luna) yang sangat canggih dan datang dari masa depan untuk membunuhnya. Kelangsungan hidup Dani bergantung pada kekuatannya bersama Grace (Mackenzie Davis), Grace, seorang manusia super yang juga dikirim dari masa depan dan seorang Sarah Connor (Linda Hamilton). Keduanya membantu Dani melawan Terminator itu. Rev 9 dikirim ke masa lalu untuk menghentikan manusia bangkit dan mengambil alih Skynet. Rev 9 tampak seperti kombinasi dari T-800 dan T-1000, seperti yang terlihat dalam The",
            popularity= 186.953,
            posterPath= "/i8QWXu6dGuTKKerJtnd0A4lUpbv.jpg",
            releaseDate= "2019-10-23",
            title= "Terminator: Dark Fate",
            video= false,
            voteAverage= 6.5,
            voteCount= 3528
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/spYx9XQFODuqEVoPpvaJI1ksAVt.jpg",
            genreIds= listOf(28, 53, 18),
            id= 522938,
            originalLanguage= "en",
            originalTitle= "Rambo: Last Blood",
            overview= "Ketika putri pengurus rumah tangganya diculik, Rambo melintasi perbatasan AS-Meksiko untuk membawanya pulang tetapi mendapati dirinya menghadapi kekuatan penuh salah satu kartel paling kejam di Meksiko.",
            popularity= 172.666,
            posterPath= "/7u1c5rNsiPLL37Vl6AsBC3bs0ZZ.jpg",
            releaseDate= "2019-09-19",
            title= "Rambo: Last Blood",
            video= false,
            voteAverage= 6.5,
            voteCount= 2651
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/nN4Gs3vZAOJ1D6FRtrwbU9VGYwU.jpg",
            genreIds= listOf(16, 10749, 10751),
            id= 486589,
            originalLanguage= "en",
            originalTitle= "Red Shoes And The Seven Dwarfs",
            overview= "",
            popularity= 179.663,
            posterPath= "/MBiKqTsouYqAACLYNDadsjhhC0.jpg",
            releaseDate= "2019-07-25",
            title= "Red Shoes And The Seven Dwarfs",
            video= false,
            voteAverage= 7.8,
            voteCount= 733
        ))
        movies.add(ResultsItemMovie(
            adult= false,
            backdropPath= "/uicia399gyMGE1smatJ41M0CtFx.jpg",
            genreIds= listOf(16, 28, 12, 14),
            id= 505262,
            originalLanguage= "ja",
            originalTitle= "僕のヒーローアカデミア THE MOVIE ～2人の英雄～",
            overview= "",
            popularity= 195.072,
            posterPath= "/rwLuZhDcLbtC8VKW8Z2xnNKTsAJ.jpg",
            releaseDate= "2018-08-03",
            title= "僕のヒーローアカデミア THE MOVIE ～2人の英雄～",
            video= false,
            voteAverage= 8.0,
            voteCount= 627
        ))
        return movies
    }

    fun generateDummyDetailMovieResponse(): DetailMovieResponse{
        return DetailMovieResponse(
                adult= false,
                backdropPath= "/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg",
                belongsToCollection= null,
                budget= 17700000,
                genres= listOf(
                        GenresItemMovie(id= 28, name= "Action"),
                        GenresItemMovie(id= 12, name= "Adventure"),
                        GenresItemMovie(id= 53, name= "Thriller")
                ),
                homepage= "",
                id= 581387,
                imdbId= "tt11285908",
                originalLanguage= "ko",
                originalTitle= "백두산",
                overview= "Bencana mengguncang Korea secara tak terduga. Ketika Baekdu - gunung tertinggi di Korea meletus dan menyemburkan abu ke atmosfer. Petaka besar kini mengancam Seoul (Korea Selatan) maupun Pyongyang (Korea Utara). Untuk menghadapi bencana ini pakar peledak Korea Selatan (Ha Jung Woo) harus bekerja sama dengan pejabat khusus Korea Utara (Lee Byung Hun) serta pakar geologi nomor satu (Ma Dong Seok) untuk menghentikan bencana dahsyat yang dapat menyebabkan Korea menghilang dari peta dunia untuk selamanya. Sebuah film bencana persembahan Dexter Studios yang telah sukses menghadirkan kisah epik Along With The Gods.",
                popularity= 608.219,
                posterPath= "/arHW8z3uHVknHc24dvc1pQvxjw.jpg",
                productionCompanies= listOf(
                        ProductionCompaniesItemMovie(
                                id= 103323,
                                logoPath= "/6erRU1smLcM353NKVldsYyAFh56.png",
                                name= "Dexter Studios",
                                originCountry= "KR"),
                        ProductionCompaniesItemMovie(
                                id= 7036,
                                logoPath= "/javbyY0ZCvlFJtly3tpZqf2NwLX.png",
                                name= "CJ Entertainment",
                                originCountry= "KR"),
                        ProductionCompaniesItemMovie(
                                id= 7036,
                                logoPath= "/javbyY0ZCvlFJtly3tpZqf2NwLX.png",
                                name= "CJ Entertainment",
                                originCountry= "KR"),
                        ProductionCompaniesItemMovie(
                                id= 112425,
                                logoPath= "/2y7W6sMH5AtKjKnPDWJzKv1J4Xx.png",
                                name= "Perfect Storm Film",
                                originCountry= "KR"),
                        ProductionCompaniesItemMovie(
                                id= 126469,
                                logoPath= null,
                                name= "Dexter Pictures",
                                originCountry= "KR")
                ),
                productionCountries= listOf(
                        ProductionCountriesItemMovie(iso31661= "KR", name= "South Korea")
                ),
                releaseDate= "2019-12-19",
                revenue= 61321941,
                runtime= 128,
                spokenLanguages= listOf(
                        SpokenLanguagesItemMovie(englishName="Korean", iso6391="ko", name="한국어/조선말"),
                        SpokenLanguagesItemMovie(englishName="English", iso6391="en", name="English")
                ),
                status= "Released",
                tagline= "",
                title= "Ashfall",
                video= false,
                voteAverage= 6.4,
                voteCount= 276
        )
    }

    fun generateDummyTVShowsResponse(): ArrayList<ResultsItemTVShow>{
        val tvShows = ArrayList<ResultsItemTVShow>()
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/ykElAtsOBoArgI1A8ATVH0MNve0.jpg",
                firstAirDate= "2021-06-09",
                genreIds= listOf(18, 10765),
                id= 84958,
                name= "Loki",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "Loki",
                overview= "Penjahat lincah Loki melanjutkan perannya sebagai Dewa Mischief setelah peristiwa \"Avengers: Endgame\".",
                popularity= 5171.482,
                posterPath= "/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
                voteAverage= 8.1,
                voteCount= 3478
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/1qOA3kMtQO8bjnW8M2smjA8tp10.jpg",
                firstAirDate= "2018-10-05",
                genreIds= listOf(80, 9648, 18),
                id= 76669,
                name= "Elite",
                originCountry= listOf("ES"),
                originalLanguage= "es",
                originalName= "Élite",
                overview= "Ketika tiga anak kelas pekerja mendaftar di sekolah paling eksklusif di Spanyol, bentrokan antara siswa kaya dan miskin menyebabkan tragedi.",
                popularity= 3453.195,
                posterPath= "/8fcYtdB6HLP7gsj46OKZ24PjC1g.jpg",
                voteAverage= 8.2,
                voteCount= 6823
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/9Jmd1OumCjaXDkpllbSGi2EpJvl.jpg",
                firstAirDate= "2014-10-07",
                genreIds= listOf(18, 10765),
                id= 60735,
                name= "Kilat",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "The Flash",
                overview= "Setelah akselerator partikel menyebabkan badai aneh, Penyelidik CSI Barry Allen disambar petir dan jatuh koma. Beberapa bulan kemudian dia terbangun dengan kekuatan kecepatan super, memberinya kemampuan untuk bergerak melalui Central City seperti malaikat penjaga yang tak terlihat. Meskipun awalnya senang dengan kekuatan barunya, Barry terkejut menemukan bahwa dia bukan satu-satunya \"manusia meta\" yang diciptakan setelah ledakan akselerator - dan tidak semua orang menggunakan kekuatan baru mereka untuk kebaikan. Barry bermitra dengan S.T.A.R. Lab dan mendedikasikan hidupnya untuk melindungi yang tidak bersalah. Untuk saat ini, hanya beberapa teman dekat dan rekan yang tahu bahwa Barry secara harfiah adalah manusia tercepat, tetapi tidak lama sebelum dunia mengetahui apa yang menjadi Barry Allen ... The Flash.",
                popularity= 1575.343,
                posterPath= "/wHa6KOJAoNTFLFtp7wguUJKSnju.jpg",
                voteAverage= 7.7,
                voteCount= 7869
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/h48Dpb7ljv8WQvVdyFWVLz64h4G.jpg",
                firstAirDate= "2016-01-25",
                genreIds= listOf(80, 10765),
                id= 63174,
                name= "Lucifer",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "Lucifer",
                overview= "Bosan dan tidak bahagia sebagai Penguasa Neraka, Lucifer Morningstar meninggalkan tahtanya dan pensiun ke Los Angeles, di mana ia telah bekerja sama dengan detektif LAPD Chloe Decker untuk menjatuhkan penjahat. Tapi semakin lama dia menjauh dari dunia bawah, semakin besar ancaman bahwa yang terburuk dari umat manusia dapat melarikan diri.",
                popularity= 1201.503,
                posterPath= "/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg",
                voteAverage= 8.5,
                voteCount= 9334
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/lucFMV4qxvpsti5xnN6paUxCbAn.jpg",
                firstAirDate= "2021-06-17",
                genreIds= listOf(18),
                id= 126525,
                name= "Elite Histórias Breves: Carla Samuel",
                originCountry= listOf(),
                originalLanguage= "es",
                originalName= "Elite Histórias Breves: Carla Samuel",
                overview= "",
                popularity= 1057.837,
                posterPath= "/xTcID7kgEa932O0BBqsJxRO67za.jpg",
                voteAverage= 8.0,
                voteCount= 110
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/pPKiIJEEcV0E1hpVcWRXyp73ZpX.jpg",
                firstAirDate= "2021-02-23",
                genreIds= listOf(10765, 10759, 18),
                id= 95057,
                name= "Superman & Lois",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "Superman & Lois",
                overview= "",
                popularity= 943.162,
                posterPath= "/vlv1gn98GqMnKHLSh0dNciqGfBl.jpg",
                voteAverage= 8.3,
                voteCount= 986
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/iDbIEpCM9nhoayUDTwqFL1iVwzb.jpg",
                firstAirDate= "2017-09-25",
                genreIds= listOf(18),
                id= 71712,
                name= "The Good Doctor",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "The Good Doctor",
                overview= "",
                popularity= 877.343,
                posterPath= "/z1K4mJwISETia59rrnMdXxzoSrZ.jpg",
                voteAverage= 8.6,
                voteCount= 8681
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/xpba0Dxz3sxV3QgYLR8UIe1LAAX.jpg",
                firstAirDate= "2021-06-04",
                genreIds= listOf(18, 10765),
                id= 103768,
                name= "Sweet Tooth",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "Sweet Tooth",
                overview= "",
                popularity= 861.919,
                posterPath= "/rgMfhcrVZjuy5b7Pn0KzCRCEnMX.jpg",
                voteAverage= 8.0,
                voteCount= 433
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/6LfVuZBiOOCtqch5Ukspjb9y0EB.jpg",
                firstAirDate= "2013-12-02",
                genreIds= listOf(16, 35, 10765, 10759),
                id= 60625,
                name= "Rick and Morty",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "Rick and Morty",
                overview= "Rick adalah orang tua yang tidak seimbang secara mental tetapi berbakat secara ilmiah yang baru-baru ini terhubung kembali dengan keluarganya. Dia menghabiskan sebagian besar waktunya dengan melibatkan cucunya yang muda, Morty, dalam petualangan berbahaya dan aneh di luar angkasa dan alam semesta alternatif. Ditambah dengan kehidupan keluarga Morty yang sudah tidak stabil, peristiwa-peristiwa ini menyebabkan Morty sangat tertekan di rumah dan sekolah.",
                popularity= 821.017,
                posterPath= "/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg",
                voteAverage= 8.8,
                voteCount= 4440
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/edmk8xjGBsYVIf4QtLY9WMaMcXZ.jpg",
                firstAirDate= "2005-03-27",
                genreIds= listOf(18),
                id= 1416,
                name= "Anatomi Grey",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "Grey's Anatomy",
                overview= "Ikuti kehidupan pribadi dan profesional sekelompok dokter di Rumah Sakit Gray Sloan Memorial di Seattle.",
                popularity= 756.203,
                posterPath= "/clnyhPqj1SNgpAdeSS6a6fwE6Bo.jpg",
                voteAverage= 8.2,
                voteCount= 6285
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/b0WmHGc8LHTdGCVzxRb3IBMur57.jpg",
                firstAirDate= "2021-03-19",
                genreIds= listOf(10765, 10759, 18, 10768),
                id= 88396,
                name= "The Falcon and the Winter Soldier",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "The Falcon and the Winter Soldier",
                overview= "",
                popularity= 753.943,
                posterPath= "/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
                voteAverage= 7.8,
                voteCount= 5958
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/3IPmnpvYHWspBbSG4ERp45yWdQ4.jpg",
                firstAirDate= "2021-06-15",
                genreIds= listOf(18),
                id= 126526,
                name= "Elite Histórias Breves: Nadia Guzmán",
                originCountry= listOf(),
                originalLanguage= "es",
                originalName= "Elite Histórias Breves: Nadia Guzmán",
                overview= "",
                popularity= 704.595,
                posterPath= "/gLEmXLqzN8JkLaLh0G9XohzLmzV.jpg",
                voteAverage= 7.9,
                voteCount= 81
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/wu444tM9YBllq9UcBv5TeidO3j3.jpg",
                firstAirDate= "2020-01-31",
                genreIds= listOf(18, 10765, 9648),
                id= 91557,
                name= "Ragnarok",
                originCountry= listOf("NO"),
                originalLanguage= "no",
                originalName= "Ragnarok",
                overview= "",
                popularity= 641.087,
                posterPath= "/1LRLLWGvs5sZdTzuMqLEahb88Pc.jpg",
                voteAverage= 8.1,
                voteCount= 485
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/qZtAf4Z1lazGQoYVXiHOrvLr5lI.jpg",
                firstAirDate= "2017-01-26",
                genreIds= listOf(9648, 18, 80),
                id= 69050,
                name= "Riverdale",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "Riverdale",
                overview= "Ditetapkan di masa sekarang, seri ini menawarkan pandangan subversif yang berani pada Archie, Betty, Veronica dan teman-teman mereka, menjelajahi surealitas kehidupan kota kecil, kegelapan dan keanehan yang menggelegak di bawah fasad Riverdale yang sehat.",
                popularity= 563.037,
                posterPath= "/6zBWSuYW3Ps1nTfeMS8siS4KUaA.jpg",
                voteAverage= 8.6,
                voteCount= 11470
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/ro2nKGja5KHPNFxvmI2QsEU9Y4E.jpg",
                firstAirDate= "2021-01-08",
                genreIds= listOf(80, 18, 9648),
                id= 96677,
                name= "Lupin",
                originCountry= listOf("FR"),
                originalLanguage= "fr",
                originalName= "Lupin",
                overview= "",
                popularity= 524.09,
                posterPath= "/sgxawbFB5Vi5OkPWQLNfl3dvkNJ.jpg",
                voteAverage= 7.9,
                voteCount= 971
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/5b5ZZGECl4FLDBKn3zJ6w6GBPRg.jpg",
                firstAirDate= "2021-06-17",
                genreIds= listOf(35, 18),
                id= 119243,
                name= "iCarly",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "iCarly",
                overview= "",
                popularity= 483.609,
                posterPath= "/s5k4GqTUGXeUdScNrjpYfiQLKHI.jpg",
                voteAverage= 8.4,
                voteCount= 113
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/pnyT1foDmmXTsho2DfxN2ePI8ix.jpg",
                firstAirDate= "2018-06-12",
                genreIds= listOf(18),
                id= 80240,
                name= "La Reina del Flow",
                originCountry= listOf("CO"),
                originalLanguage= "es",
                originalName= "La Reina del Flow",
                overview= "",
                popularity= 475.403,
                posterPath= "/fuVuDYrs8sxvEolnYr0wCSvtyTi.jpg",
                voteAverage= 8.0,
                voteCount= 857
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
                firstAirDate= "2011-04-17",
                genreIds= listOf(10765, 18, 10759),
                id= 1399,
                name= "Game of Thrones",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "Game of Thrones",
                overview= "Tujuh keluarga bangsawan berjuang untuk menguasai tanah mitos Westeros. Gesekan antara rumah-rumah mengarah ke perang skala penuh. Semua sementara kejahatan yang sangat kuno terbangun di utara terjauh. Di tengah-tengah perang, perintah militer yang diabaikan, Night's Watch, adalah yang berdiri di antara alam manusia dan kengerian es di luarnya.",
                popularity= 470.44,
                posterPath= "/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
                voteAverage= 8.4,
                voteCount= 14809
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/fRYwdeNjMqC30EhofPx5PlDpdun.jpg",
                firstAirDate= "2018-10-25",
                genreIds= listOf(10765, 18),
                id= 79460,
                name= "Legacies",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "Legacies",
                overview= "",
                popularity= 465.828,
                posterPath= "/qTZIgXrBKURBK1KrsT7fe3qwtl9.jpg",
                voteAverage= 8.6,
                voteCount= 1980
        ))
        tvShows.add(ResultsItemTVShow(
                backdropPath= "/rFLF2QTZL37Yjdc6kmV0PbrYz3w.jpg",
                firstAirDate= "2021-01-15",
                genreIds= listOf(10765, 9648, 18),
                id= 85271,
                name= "WandaVision",
                originCountry= listOf("US"),
                originalLanguage= "en",
                originalName= "WandaVision",
                overview= "Wanda Maximoff dan Vision — dua makhluk bertenaga super yang menjalani kehidupan pinggiran kota yang ideal — mulai curiga bahwa semuanya tidak seperti yang terlihat.",
                popularity= 452.741,
                posterPath= "/frobUz2X5Pc8OiVZU8Oo5K3NKMM.jpg",
                voteAverage= 8.4,
                voteCount= 8700
        ))
        return tvShows
    }

    fun generateDummyDetailTVShowResponse(): DetailTVShowResponse{
        return DetailTVShowResponse(
                backdropPath= "/ykElAtsOBoArgI1A8ATVH0MNve0.jpg",
                createdBy= listOf(
                        CreatedByItem(
                                id = 2094567,
                                creditId = "6001713e7390c0003df730af",
                                name = "Michael Waldron",
                                gender = 2,
                                profilePath = "/5d6wkYnJgkVAzThqnnwOLNDzACM.jpg"
                        )
                ),
        episodeRunTime= listOf(52),
        firstAirDate= "2021-06-09",
        genres= listOf(
                GenresItem(id = 18, name = "Drama"),
                GenresItem(id = 10765, name = "Sci-fi & Fantasy")
        ),
        homepage= "https://www.disneyplus.com/series/wp/6pARMvILBGzF",
        id= 84958,
        inProduction= true,
        languages= listOf("en"),
        lastAirDate= "2021-06-16",
        lastEpisodeToAir= LastEpisodeToAir(
                airDate= "2021-06-16",
                episodeNumber= 2,
                id= 2927202,
                name= "",
                overview= "",
                productionCode= "",
                seasonNumber= 1,
                stillPath= "/gqpcfkdmSsm6xiX2EsLkwUvA8g8.jpg",
                voteAverage= 7.286,
                voteCount= 7
        ),
        name= "Loki",
        nextEpisodeToAir= NextEpisodeToAir(
                airDate= "2021-06-23",
                episodeNumber= 3,
                id= 2927203,
                name= "",
                overview= "",
                productionCode= "",
                seasonNumber= 1,
                stillPath= null,
                voteAverage= 0.0,
                voteCount= 0
        ),
        networks= listOf(
                NetworksItem(
                        name= "Disney+",
                        id= 2739,
                        logoPath= "/gJ8VX6JSu3ciXHuC2dDGAo2lvwM.png",
                        originCountry= "US")
        ),
        numberOfEpisodes= 6,
        numberOfSeasons= 1,
        originCountry= listOf("US"),
        originalLanguage= "en",
        originalName= "Loki",
        overview= "Penjahat lincah Loki melanjutkan perannya sebagai Dewa Mischief setelah peristiwa \"Avengers: Endgame\".",
        popularity= 5171.482,
        posterPath= "/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
        productionCompanies= listOf(
                ProductionCompaniesItemTVShow(
                        id= 420,
                        logoPat= "/hUzeosd33nzE5MCNsZxCGEKTXaQ.png",
                        name= "Marvel Studios",
                        originCountry= "US"
                )),
        productionCountries= listOf(
            ProductionCountriesItemTVShow(
                iso31661= "US",
                name= "United States of America"
            )
        ),
        seasons= listOf(SeasonsItem(
            airDate= "2021-06-08",
            episodeCount= 6,
            id= 114355,
        name= "Musim ke 1",
        overview= "",
        posterPath= "/8uVqe9ThcuYVNdh4O0kuijIWMLL.jpg",
        seasonNumber= 1
        )),
        spokenLanguages= listOf(
                    SpokenLanguagesItemTVShow(
                        englishName= "English",
                        iso6391= "en",
                        name= "English"
                    )
        ),
        status= "Returning Series",
        tagline= "",
        type= "Miniseries",
        voteAverage= 8.1,
        voteCount= 3520
        )
    }
}